Remove unsupported release.toml setting
embedded-graphics/tinytga pull request #19
Opened 2023-05-16 17:45 UTC by rfuest

Remove unsupported release.toml setting

2023-05-16 18:59 UTC, jamwaffles requested changes

2023-05-16 18:59 UTC, jamwaffles commented on release.toml
> -no-dev-version = true
GH won't let me add a suggestion but I've switched this to `dev-version = false` in other projects, which retains the current behaviour.

2023-05-16 19:02 UTC, jamwaffles approved these changes
Ah ignore me, I didn't know the option was removed entirely upstream.

2023-05-17 01:06 UTC, rfuest commented
> Ah ignore me, I didn't know the option was removed entirely upstream.

This did also confuse me when I searched the `cargo-release` changelog for a replacement and didn't notice that the replacement had also be removed.

2023-05-17 01:07 UTC, merged

2023-05-17 09:05 UTC, jamwaffles commented
I've just released new versions of both crates. I'm not sure why the permissions won't let you release yourself. I haven't changed anything in a long time, so maybe Github updated something on their side.

2023-05-17 14:35 UTC, rfuest commented
Thanks. I'm not 100% sure if it would have failed, perhaps I messed something else up and got the git error message because of that.